# use the latest ubuntu environment (18.04) available on travis
language: go

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.14 lands.
env:
  - GO111MODULE=on

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.12.x
  - master
  - tip

# Only clone the most recent commit.
git:
  depth: 1

notifications:
  email:
    - langyu0826@gmail.com

install:
  - make tools

script:
  - env GO111MODULE=on make lint && make report-coverage

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      name: "Semantic Release"
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script:
      #   - make
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # Use nvm to install and use the Node LTS version (nvm is installed on all Travis images)
          - nvm install lts/*
          - npx semantic-release
